#!/usr/bin/env python3
"""
Generate the two comparison project configs (masked vs mask-free) for the
robust-keypoint training program, by INHERITING a proven base config so all
rig/training values (IMAGE_SIZE, BOUNDING_BOX_SIZE, ROI_CUBE_SIZE, GRID_SPACING,
MODEL_SIZE, LR, epochs, ...) carry over unchanged. Only the things that should
differ are overridden:

  * DATASET.DATASET_2D / DATASET_3D -> the unified dataset (absolute path)
  * KEYPOINT_NAMES / SKELETON / KEYPOINTDETECT.NUM_JOINTS -> from the dataset
  * HYBRIDNET.NUM_CAMERAS -> from the dataset's images
  * KEYPOINTDETECT.INSTANCE_MASK_INPUT -> True (masked arm) / False (mask-free)
  * KEYPOINTDETECT.SAM3_MASKS_DIRNAME -> 'sam3_masks' (masked arm only)

Use the existing courtship project's config as --base-config so the new
projects reproduce its proven setup for this 7-camera rig:

  python scripts/make_unified_project.py \
      --base-config projects/merge_courtship_V3/config.yaml \
      --dataset /data2/users/eabe/datasets/Johnson_lab/red_data/red_data_unified_V2 \
      --prefix unified_V2
"""

import argparse
import json
import os
from pathlib import Path

import yaml


def load_dataset_meta(dataset_root):
    coco = json.load(open(Path(dataset_root) / "annotations" / "instances_train.json"))
    kp_names = list(coco["keypoint_names"])
    # skeleton entries are dicts {keypointA, keypointB, ...} -> [A, B] pairs
    skeleton = [[s["keypointA"], s["keypointB"]] for s in coco["skeleton"]
                if s["keypointA"] in kp_names and s["keypointB"] in kp_names]
    cams = sorted({im["file_name"].split("/")[1] for im in coco["images"]})
    return kp_names, skeleton, len(cams)


def write_config(base, dataset_root, kp_names, skeleton, num_cams,
                 instance_mask, out_path):
    cfg = dict(base)  # shallow copy; we overwrite whole subsections below
    cfg.setdefault("DATASET", {})
    cfg["DATASET"] = dict(cfg.get("DATASET", {}))
    cfg["DATASET"]["DATASET_2D"] = str(dataset_root)
    cfg["DATASET"]["DATASET_3D"] = str(dataset_root)

    cfg["KEYPOINTDETECT"] = dict(cfg.get("KEYPOINTDETECT", {}))
    cfg["KEYPOINTDETECT"]["NUM_JOINTS"] = len(kp_names)
    cfg["KEYPOINTDETECT"]["INSTANCE_MASK_INPUT"] = bool(instance_mask)
    if instance_mask:
        cfg["KEYPOINTDETECT"]["SAM3_MASKS_DIRNAME"] = "sam3_masks"

    cfg["HYBRIDNET"] = dict(cfg.get("HYBRIDNET", {}))
    cfg["HYBRIDNET"]["NUM_CAMERAS"] = num_cams

    cfg["KEYPOINT_NAMES"] = kp_names
    cfg["SKELETON"] = skeleton

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write("# Auto-generated by scripts/make_unified_project.py\n")
        f.write(f"# base: inherited proven rig/training values\n")
        f.write(f"# INSTANCE_MASK_INPUT={bool(instance_mask)}\n")
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    print(f"wrote {out_path}  (INSTANCE_MASK_INPUT={bool(instance_mask)}, "
          f"num_joints={len(kp_names)}, num_cameras={num_cams})")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base-config", required=True, type=Path,
                    help="proven project config to inherit (e.g. merge_courtship_V3)")
    ap.add_argument("--dataset", required=True, type=Path)
    ap.add_argument("--prefix", default="unified_V2")
    ap.add_argument("--projects-dir", type=Path,
                    default=Path(__file__).resolve().parent.parent / "projects")
    args = ap.parse_args()

    base = yaml.safe_load(args.base_config.open())
    kp_names, skeleton, num_cams = load_dataset_meta(args.dataset)

    write_config(base, args.dataset, kp_names, skeleton, num_cams,
                 instance_mask=True,
                 out_path=args.projects_dir / f"{args.prefix}_masked" / "config.yaml")
    write_config(base, args.dataset, kp_names, skeleton, num_cams,
                 instance_mask=False,
                 out_path=args.projects_dir / f"{args.prefix}_maskfree" / "config.yaml")
    print("\nNext: train each arm (Hyak), e.g.")
    print(f"  python tools/run_train.py CenterDetect   {args.prefix}_masked --epochs 50")
    print(f"  python tools/run_train.py KeypointDetect {args.prefix}_masked --pretrain latest")
    print(f"  python tools/run_train.py HybridNet      {args.prefix}_masked --weights-kp latest")
    print("  (repeat for *_maskfree) then compare with tools/eval_per_condition.py")


if __name__ == "__main__":
    main()
